FROM golang:1.22-alpine

WORKDIR /app

# Install air for hot-reloading
RUN go install github.com/cosmtrek/air@latest

# Copy modules and download dependencies first to leverage build cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Expose the port
EXPOSE 8080

# Run 'air' which will watch for file changes and re-build/re-run
CMD ["air"]
