FROM golang:1.25-alpine

WORKDIR /app

# Install air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Copy modules and download dependencies first to leverage build cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Expose the port
EXPOSE 8080

# Run 'air' which will watch for file changes and re-build/re-run
CMD ["air"]
