name: Go CI Workflow

on:
  push:
    branches: [ "master", "docker", "backend" ]
  pull_request:
    branches: [ "master", "docker", "backend" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Run Tests
        working-directory: ./backend
        run: go test -v ./...

      - name: Build Application
        working-directory: ./backend
        run: go build -v ./...
